package com.example.my_kmp_project.feature.mine

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/**
 * OHOS-safe Mine icons (custom ImageVector — no material-icons-extended).
 * Inventory: header (info/calendar/settings/logout/login), quick services
 * (bag/card/play/doc), functions (sms/calc/car/play/build/qr/support/chart),
 * meta (creditcard/chevronDown/check).
 */
internal object MineIcons {
    val Info: ImageVector by lazy { info() }
    val Calendar: ImageVector by lazy { calendar() }
    val Settings: ImageVector by lazy { settings() }
    val Logout: ImageVector by lazy { logout() }
    val Login: ImageVector by lazy { login() }
    val Bag: ImageVector by lazy { bag() }
    val CreditCard: ImageVector by lazy { creditCard() }
    val PlayRect: ImageVector by lazy { playRect() }
    val DocText: ImageVector by lazy { docText() }
    val Sms: ImageVector by lazy { sms() }
    val Calculate: ImageVector by lazy { calculate() }
    val Car: ImageVector by lazy { car() }
    val PlayCircle: ImageVector by lazy { playCircle() }
    val Build: ImageVector by lazy { build() }
    val QrCode: ImageVector by lazy { qrCode() }
    val Support: ImageVector by lazy { support() }
    val Chart: ImageVector by lazy { chart() }
    val ChevronDown: ImageVector by lazy { chevronDown() }
    val Check: ImageVector by lazy { check() }

    private fun solid(block: androidx.compose.ui.graphics.vector.PathBuilder.() -> Unit): ImageVector =
        ImageVector.Builder(
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                fillAlpha = 1f,
                stroke = null,
                strokeAlpha = 1f,
                strokeLineWidth = 1f,
                strokeLineCap = StrokeCap.Butt,
                strokeLineJoin = StrokeJoin.Miter,
                strokeLineMiter = 1f,
                pathFillType = PathFillType.NonZero,
                pathBuilder = block,
            )
        }.build()

    private fun info() = solid {
        moveTo(12f, 2f)
        curveTo(6.48f, 2f, 2f, 6.48f, 2f, 12f)
        reflectiveCurveToRelative(4.48f, 10f, 10f, 10f)
        reflectiveCurveToRelative(10f, -4.48f, 10f, -10f)
        reflectiveCurveTo(17.52f, 2f, 12f, 2f)
        close()
        moveTo(11f, 7f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        close()
        moveTo(11f, 11f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(6f)
        horizontalLineToRelative(-2f)
        close()
    }

    private fun calendar() = solid {
        moveTo(19f, 4f)
        horizontalLineToRelative(-1f)
        verticalLineTo(2f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(2f)
        horizontalLineTo(8f)
        verticalLineTo(2f)
        horizontalLineTo(6f)
        verticalLineToRelative(2f)
        horizontalLineTo(5f)
        curveToRelative(-1.11f, 0f, -2f, 0.9f, -2f, 2f)
        verticalLineToRelative(14f)
        curveToRelative(0f, 1.1f, 0.89f, 2f, 2f, 2f)
        horizontalLineToRelative(14f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineTo(6f)
        curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
        close()
        moveTo(19f, 20f)
        horizontalLineTo(5f)
        verticalLineTo(10f)
        horizontalLineToRelative(14f)
        verticalLineToRelative(10f)
        close()
        moveTo(19f, 8f)
        horizontalLineTo(5f)
        verticalLineTo(6f)
        horizontalLineToRelative(14f)
        verticalLineToRelative(2f)
        close()
    }

    private fun settings() = solid {
        moveTo(19.14f, 12.94f)
        curveToRelative(0.04f, -0.31f, 0.06f, -0.63f, 0.06f, -0.94f)
        curveToRelative(0f, -0.31f, -0.02f, -0.63f, -0.06f, -0.94f)
        lineToRelative(2.03f, -1.58f)
        curveToRelative(0.18f, -0.14f, 0.23f, -0.41f, 0.12f, -0.61f)
        lineToRelative(-1.92f, -3.32f)
        curveToRelative(-0.12f, -0.22f, -0.37f, -0.29f, -0.59f, -0.22f)
        lineToRelative(-2.39f, 0.96f)
        curveToRelative(-0.5f, -0.38f, -1.03f, -0.7f, -1.62f, -0.94f)
        lineTo(14.4f, 2.81f)
        curveToRelative(-0.04f, -0.24f, -0.24f, -0.41f, -0.48f, -0.41f)
        horizontalLineToRelative(-3.84f)
        curveToRelative(-0.24f, 0f, -0.43f, 0.17f, -0.47f, 0.41f)
        lineTo(9.25f, 5.35f)
        curveTo(8.66f, 5.59f, 8.12f, 5.92f, 7.63f, 6.29f)
        lineTo(5.24f, 5.33f)
        curveToRelative(-0.22f, -0.08f, -0.47f, 0f, -0.59f, 0.22f)
        lineTo(2.74f, 8.87f)
        curveTo(2.62f, 9.08f, 2.66f, 9.34f, 2.86f, 9.48f)
        lineToRelative(2.03f, 1.58f)
        curveTo(4.84f, 11.37f, 4.8f, 11.69f, 4.8f, 12f)
        reflectiveCurveToRelative(0.02f, 0.63f, 0.06f, 0.94f)
        lineToRelative(-2.03f, 1.58f)
        curveToRelative(-0.18f, 0.14f, -0.23f, 0.41f, -0.12f, 0.61f)
        lineToRelative(1.92f, 3.32f)
        curveToRelative(0.12f, 0.22f, 0.37f, 0.29f, 0.59f, 0.22f)
        lineToRelative(2.39f, -0.96f)
        curveToRelative(0.5f, 0.38f, 1.03f, 0.7f, 1.62f, 0.94f)
        lineToRelative(0.36f, 2.54f)
        curveToRelative(0.05f, 0.24f, 0.24f, 0.41f, 0.48f, 0.41f)
        horizontalLineToRelative(3.84f)
        curveToRelative(0.24f, 0f, 0.44f, -0.17f, 0.47f, -0.41f)
        lineToRelative(0.36f, -2.54f)
        curveToRelative(0.59f, -0.24f, 1.13f, -0.56f, 1.62f, -0.94f)
        lineToRelative(2.39f, 0.96f)
        curveToRelative(0.22f, 0.08f, 0.47f, 0f, 0.59f, -0.22f)
        lineToRelative(1.92f, -3.32f)
        curveToRelative(0.12f, -0.22f, 0.07f, -0.47f, -0.12f, -0.61f)
        lineToRelative(-2.01f, -1.58f)
        close()
        moveTo(12f, 15.6f)
        curveToRelative(-1.98f, 0f, -3.6f, -1.62f, -3.6f, -3.6f)
        reflectiveCurveToRelative(1.62f, -3.6f, 3.6f, -3.6f)
        reflectiveCurveToRelative(3.6f, 1.62f, 3.6f, 3.6f)
        reflectiveCurveToRelative(-1.62f, 3.6f, -3.6f, 3.6f)
        close()
    }

    private fun logout() = solid {
        moveTo(10.09f, 15.59f)
        lineTo(11.5f, 17f)
        lineToRelative(5f, -5f)
        lineToRelative(-5f, -5f)
        lineToRelative(-1.41f, 1.41f)
        lineTo(12.67f, 11f)
        horizontalLineTo(3f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(9.67f)
        lineToRelative(-2.58f, 2.59f)
        close()
        moveTo(19f, 3f)
        horizontalLineTo(5f)
        curveToRelative(-1.11f, 0f, -2f, 0.9f, -2f, 2f)
        verticalLineToRelative(4f)
        horizontalLineToRelative(2f)
        verticalLineTo(5f)
        horizontalLineToRelative(14f)
        verticalLineToRelative(14f)
        horizontalLineTo(5f)
        verticalLineToRelative(-4f)
        horizontalLineTo(3f)
        verticalLineToRelative(4f)
        curveToRelative(0f, 1.1f, 0.89f, 2f, 2f, 2f)
        horizontalLineToRelative(14f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineTo(5f)
        curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
        close()
    }

    private fun login() = solid {
        moveTo(12f, 12f)
        curveToRelative(2.21f, 0f, 4f, -1.79f, 4f, -4f)
        reflectiveCurveToRelative(-1.79f, -4f, -4f, -4f)
        reflectiveCurveToRelative(-4f, 1.79f, -4f, 4f)
        reflectiveCurveToRelative(1.79f, 4f, 4f, 4f)
        close()
        moveTo(12f, 14f)
        curveToRelative(-2.67f, 0f, -8f, 1.34f, -8f, 4f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(16f)
        verticalLineToRelative(-2f)
        curveToRelative(0f, -2.66f, -5.33f, -4f, -8f, -4f)
        close()
        moveTo(17f, 8f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        close()
    }

    private fun bag() = solid {
        moveTo(18f, 6f)
        horizontalLineToRelative(-2f)
        curveToRelative(0f, -2.21f, -1.79f, -4f, -4f, -4f)
        reflectiveCurveTo(8f, 3.79f, 8f, 6f)
        horizontalLineTo(6f)
        curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
        verticalLineToRelative(12f)
        curveToRelative(0f, 1.1f, 0.9f, 2f, 2f, 2f)
        horizontalLineToRelative(12f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineTo(8f)
        curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
        close()
        moveTo(12f, 4f)
        curveToRelative(1.1f, 0f, 2f, 0.9f, 2f, 2f)
        horizontalLineToRelative(-4f)
        curveToRelative(0f, -1.1f, 0.9f, -2f, 2f, -2f)
        close()
        moveTo(18f, 20f)
        horizontalLineTo(6f)
        verticalLineTo(8f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(1f)
        curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
        reflectiveCurveToRelative(1f, -0.45f, 1f, -1f)
        verticalLineTo(8f)
        horizontalLineToRelative(4f)
        verticalLineToRelative(1f)
        curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
        reflectiveCurveToRelative(1f, -0.45f, 1f, -1f)
        verticalLineTo(8f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(12f)
        close()
    }

    private fun creditCard() = solid {
        moveTo(20f, 4f)
        horizontalLineTo(4f)
        curveToRelative(-1.11f, 0f, -1.99f, 0.89f, -1.99f, 2f)
        lineTo(2f, 18f)
        curveToRelative(0f, 1.11f, 0.89f, 2f, 2f, 2f)
        horizontalLineToRelative(16f)
        curveToRelative(1.11f, 0f, 2f, -0.89f, 2f, -2f)
        verticalLineTo(6f)
        curveToRelative(0f, -1.11f, -0.89f, -2f, -2f, -2f)
        close()
        moveTo(20f, 18f)
        horizontalLineTo(4f)
        verticalLineToRelative(-6f)
        horizontalLineToRelative(16f)
        verticalLineToRelative(6f)
        close()
        moveTo(20f, 8f)
        horizontalLineTo(4f)
        verticalLineTo(6f)
        horizontalLineToRelative(16f)
        verticalLineToRelative(2f)
        close()
    }

    private fun playRect() = solid {
        moveTo(4f, 6.5f)
        curveTo(4f, 5.12f, 5.12f, 4f, 6.5f, 4f)
        horizontalLineToRelative(11f)
        curveTo(18.88f, 4f, 20f, 5.12f, 20f, 6.5f)
        verticalLineToRelative(11f)
        curveToRelative(0f, 1.38f, -1.12f, 2.5f, -2.5f, 2.5f)
        horizontalLineToRelative(-11f)
        curveTo(5.12f, 20f, 4f, 18.88f, 4f, 17.5f)
        close()
        moveTo(6.5f, 6f)
        curveTo(6.22f, 6f, 6f, 6.22f, 6f, 6.5f)
        verticalLineToRelative(11f)
        curveToRelative(0f, 0.28f, 0.22f, 0.5f, 0.5f, 0.5f)
        horizontalLineToRelative(11f)
        curveToRelative(0.28f, 0f, 0.5f, -0.22f, 0.5f, -0.5f)
        verticalLineToRelative(-11f)
        curveToRelative(0f, -0.28f, -0.22f, -0.5f, -0.5f, -0.5f)
        close()
        moveTo(10f, 8.5f)
        lineToRelative(6f, 3.5f)
        lineToRelative(-6f, 3.5f)
        close()
    }

    private fun docText() = solid {
        moveTo(14f, 2f)
        horizontalLineTo(6f)
        curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
        verticalLineToRelative(16f)
        curveToRelative(0f, 1.1f, 0.9f, 2f, 2f, 2f)
        horizontalLineToRelative(12f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineTo(8f)
        lineToRelative(-6f, -6f)
        close()
        moveTo(16f, 18f)
        horizontalLineTo(8f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(8f)
        verticalLineToRelative(2f)
        close()
        moveTo(16f, 14f)
        horizontalLineTo(8f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(8f)
        verticalLineToRelative(2f)
        close()
        moveTo(13f, 9f)
        verticalLineTo(3.5f)
        lineTo(18.5f, 9f)
        horizontalLineTo(13f)
        close()
    }

    private fun sms() = solid {
        moveTo(20f, 2f)
        horizontalLineTo(4f)
        curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
        verticalLineToRelative(18f)
        lineToRelative(4f, -4f)
        horizontalLineToRelative(14f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineTo(4f)
        curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
        close()
        moveTo(9f, 11f)
        horizontalLineTo(7f)
        verticalLineTo(9f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(13f, 11f)
        horizontalLineToRelative(-2f)
        verticalLineTo(9f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(17f, 11f)
        horizontalLineToRelative(-2f)
        verticalLineTo(9f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
    }

    private fun calculate() = solid {
        moveTo(19f, 3f)
        horizontalLineTo(5f)
        curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
        verticalLineToRelative(14f)
        curveToRelative(0f, 1.1f, 0.9f, 2f, 2f, 2f)
        horizontalLineToRelative(14f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineTo(5f)
        curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
        close()
        moveTo(13f, 7.25f)
        horizontalLineToRelative(5f)
        verticalLineToRelative(1.5f)
        horizontalLineToRelative(-5f)
        close()
        moveTo(13f, 10.25f)
        horizontalLineToRelative(5f)
        verticalLineToRelative(1.5f)
        horizontalLineToRelative(-5f)
        close()
        moveTo(13f, 13.25f)
        horizontalLineToRelative(5f)
        verticalLineToRelative(1.5f)
        horizontalLineToRelative(-5f)
        close()
        moveTo(8.5f, 18f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        close()
        moveTo(8.5f, 14.5f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        close()
        moveTo(8.5f, 11f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        close()
        moveTo(12f, 18f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        close()
        moveTo(12f, 14.5f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        close()
        moveTo(12f, 11f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        close()
    }

    private fun car() = solid {
        moveTo(18.92f, 6.01f)
        curveTo(18.72f, 5.42f, 18.16f, 5f, 17.5f, 5f)
        horizontalLineToRelative(-11f)
        curveToRelative(-0.66f, 0f, -1.21f, 0.42f, -1.42f, 1.01f)
        lineTo(3f, 12f)
        verticalLineToRelative(8f)
        curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
        horizontalLineToRelative(1f)
        curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
        verticalLineToRelative(-1f)
        horizontalLineToRelative(12f)
        verticalLineToRelative(1f)
        curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
        horizontalLineToRelative(1f)
        curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
        verticalLineToRelative(-8f)
        lineToRelative(-2.08f, -5.99f)
        close()
        moveTo(6.5f, 16f)
        curveToRelative(-0.83f, 0f, -1.5f, -0.67f, -1.5f, -1.5f)
        reflectiveCurveTo(5.67f, 13f, 6.5f, 13f)
        reflectiveCurveTo(8f, 13.67f, 8f, 14.5f)
        reflectiveCurveTo(7.33f, 16f, 6.5f, 16f)
        close()
        moveTo(17.5f, 16f)
        curveToRelative(-0.83f, 0f, -1.5f, -0.67f, -1.5f, -1.5f)
        reflectiveCurveTo(16.67f, 13f, 17.5f, 13f)
        reflectiveCurveToRelative(1.5f, 0.67f, 1.5f, 1.5f)
        reflectiveCurveTo(18.33f, 16f, 17.5f, 16f)
        close()
        moveTo(5f, 11f)
        lineToRelative(1.5f, -4.5f)
        horizontalLineToRelative(11f)
        lineTo(19f, 11f)
        horizontalLineTo(5f)
        close()
    }

    private fun playCircle() = solid {
        moveTo(12f, 2f)
        curveTo(6.48f, 2f, 2f, 6.48f, 2f, 12f)
        reflectiveCurveToRelative(4.48f, 10f, 10f, 10f)
        reflectiveCurveToRelative(10f, -4.48f, 10f, -10f)
        reflectiveCurveTo(17.52f, 2f, 12f, 2f)
        close()
        moveTo(10f, 16.5f)
        verticalLineToRelative(-9f)
        lineToRelative(6f, 4.5f)
        close()
    }

    private fun build() = solid {
        moveTo(22.7f, 19f)
        lineToRelative(-9.1f, -9.1f)
        curveToRelative(0.9f, -2.3f, 0.4f, -5f, -1.5f, -6.9f)
        curveToRelative(-2f, -2f, -5f, -2.4f, -7.4f, -1.3f)
        lineToRelative(3.7f, 3.7f)
        lineToRelative(-1.4f, 1.4f)
        lineToRelative(-3.7f, -3.7f)
        curveToRelative(-1.1f, 2.4f, -0.7f, 5.4f, 1.3f, 7.4f)
        curveToRelative(1.9f, 1.9f, 4.6f, 2.4f, 6.9f, 1.5f)
        lineToRelative(9.1f, 9.1f)
        curveToRelative(0.4f, 0.4f, 1f, 0.4f, 1.4f, 0f)
        lineToRelative(2.3f, -2.3f)
        curveToRelative(0.4f, -0.4f, 0.4f, -1.1f, 0.1f, -1.4f)
        close()
    }

    private fun qrCode() = solid {
        moveTo(3f, 11f)
        horizontalLineToRelative(8f)
        verticalLineTo(3f)
        horizontalLineTo(3f)
        verticalLineToRelative(8f)
        close()
        moveTo(5f, 5f)
        horizontalLineToRelative(4f)
        verticalLineToRelative(4f)
        horizontalLineTo(5f)
        verticalLineTo(5f)
        close()
        moveTo(3f, 21f)
        horizontalLineToRelative(8f)
        verticalLineToRelative(-8f)
        horizontalLineTo(3f)
        verticalLineToRelative(8f)
        close()
        moveTo(5f, 15f)
        horizontalLineToRelative(4f)
        verticalLineToRelative(4f)
        horizontalLineTo(5f)
        verticalLineToRelative(-4f)
        close()
        moveTo(13f, 3f)
        verticalLineToRelative(8f)
        horizontalLineToRelative(8f)
        verticalLineTo(3f)
        horizontalLineToRelative(-8f)
        close()
        moveTo(19f, 9f)
        horizontalLineToRelative(-4f)
        verticalLineTo(5f)
        horizontalLineToRelative(4f)
        verticalLineToRelative(4f)
        close()
        moveTo(19f, 19f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        close()
        moveTo(13f, 13f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        close()
        moveTo(15f, 15f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        close()
        moveTo(13f, 17f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        close()
        moveTo(15f, 19f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        close()
        moveTo(17f, 17f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        close()
        moveTo(17f, 13f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        close()
        moveTo(19f, 15f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-2f)
        close()
    }

    private fun support() = solid {
        moveTo(12f, 1f)
        curveToRelative(-4.97f, 0f, -9f, 4.03f, -9f, 9f)
        verticalLineToRelative(7f)
        curveToRelative(0f, 1.66f, 1.34f, 3f, 3f, 3f)
        horizontalLineToRelative(3f)
        verticalLineToRelative(-8f)
        horizontalLineTo(5f)
        verticalLineToRelative(-2f)
        curveToRelative(0f, -3.87f, 3.13f, -7f, 7f, -7f)
        reflectiveCurveToRelative(7f, 3.13f, 7f, 7f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-4f)
        verticalLineToRelative(8f)
        horizontalLineToRelative(4f)
        verticalLineToRelative(1f)
        horizontalLineToRelative(-7f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(6f)
        curveToRelative(1.66f, 0f, 3f, -1.34f, 3f, -3f)
        verticalLineTo(10f)
        curveToRelative(0f, -4.97f, -4.03f, -9f, -9f, -9f)
        close()
    }

    private fun chart() = solid {
        moveTo(5f, 9.2f)
        horizontalLineToRelative(3f)
        verticalLineTo(19f)
        horizontalLineTo(5f)
        close()
        moveTo(10.6f, 5f)
        horizontalLineToRelative(2.8f)
        verticalLineToRelative(14f)
        horizontalLineToRelative(-2.8f)
        close()
        moveTo(16.2f, 13f)
        horizontalLineTo(19f)
        verticalLineToRelative(6f)
        horizontalLineToRelative(-2.8f)
        close()
    }

    private fun chevronDown() = solid {
        moveTo(7.41f, 8.59f)
        lineTo(12f, 13.17f)
        lineToRelative(4.59f, -4.58f)
        lineTo(18f, 10f)
        lineToRelative(-6f, 6f)
        lineToRelative(-6f, -6f)
        close()
    }

    private fun check() = solid {
        moveTo(9f, 16.17f)
        lineTo(4.83f, 12f)
        lineToRelative(-1.42f, 1.41f)
        lineTo(9f, 19f)
        lineTo(21f, 7f)
        lineToRelative(-1.41f, -1.41f)
        close()
    }
}
